ci:
  autoupdate_schedule: monthly
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autofix_commit_msg: "style: pre-commit fixes"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "3e8a8703264a2f4a69428a0aa4dcb512790b2c8c" # frozen: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: name-tests-test
        args: ["--pytest-test-first"]
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: "3a6eb0fadf60b3cccfd80bad9dbb6fae7e47b316" # frozen: v1.10.0
    hooks:
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: "0ee178619d696787ca73d210cc191d720868c631" # frozen: v3.9.6
    hooks:
      - id: prettier
        types_or: [yaml, markdown, html, css, scss, javascript, json]
        args: [--prose-wrap=always]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "7bcc70ca475b87e0fdee2511300c74b25babe0b3" # frozen: v0.1.9
    hooks:
      - id: ruff
        args: ["--fix", "--show-fixes"]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "4daa14b20c0f48f472528c2b5f5bca28a18a7ce0" # frozen: v1.7.1
    hooks:
      - id: mypy
        files: ^(src/|tests/)
        args:
          - --ignore-missing-imports
          - --show-error-codes
        additional_dependencies: []

  - repo: https://github.com/codespell-project/codespell
    rev: "6e41aba91fb32e9feb741a6258eefeb9c6e4a482" # frozen: v2.2.6
    hooks:
      - id: codespell

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: "745eface02aef23e168a8afb6b5737818efbea95" # frozen: v0.11.0.1
    hooks:
      - id: shellcheck

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: 4b2e70d08cb2ccd26d1fba73588de41c7a5d50b7 # frozen: v0.25
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 6b63472e72e1a91ed8a2f6d483790dfb644fa1d3 # frozen: 0.37.4
    hooks:
      - id: check-dependabot
      - id: check-github-workflows
      - id: check-readthedocs

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: 451b56af716f9f0d0c2b816503a3fd0cf8b036fa # frozen: v1.29.0
    hooks:
      - id: zizmor
        files: "^\\.github"
        args: [--persona=pedantic]
