name: Minimum supported dependencies

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        # minimum supported Python
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies and force lowest bound
        run: |
          python -m pip install uv
          uv pip install --system --upgrade ".[test]"
          uv pip install --system --upgrade --resolution lowest-direct .

      - name: List installed Python packages
        run: uv pip list --system

      - name: Test with pytest
        run: pytest tests/
